apiVersion: v1
kind: Namespace
metadata:
  name: sample
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  namespace: sample
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.27
        ports:
        - containerPort: 80
        env:
        - name: SAMPLE_HOST
          valueFrom:
            secretKeyRef:
              name: sample-sealedsecret
              key: SAMPLE_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: sample
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 8080
      targetPort: 80
