apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-dep
  namespace: app
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: ghcr.io/kenta-ja8/hello-world:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        env:
        - name: SAMPLE_USER
          valueFrom:
            secretKeyRef:
              name: app-sealedsecret
              key: SAMPLE_HOST
