apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-k8s-app-server-dep
  namespace: app
spec:
  selector:
    matchLabels:
      app: home-k8s-app-server
  replicas: 3
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: home-k8s-app-server
    spec:
      containers:
      - name: home-k8s-app-server
        image: ghcr.io/kenta-ja8/home-k8s-app-server:{{ .Values.image.serverTag }}
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_HOST
          value: postgres-svc.app.svc.cluster.local
        - name: POSTGRES_DB
          value: maindb
        - name: POSTGRES_USER
          value: mainuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-sealedsecret
              key: POSTGRES_PASSWORD
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: home-k8s-app-job
  namespace: app
spec:
  schedule: "*/10 * * * *"
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: home-k8s-app-job
              image: ghcr.io/kenta-ja8/home-k8s-app-job:{{ .Values.image.jobTag }}
              args:
                - "sample"
              env:
              - name: POSTGRES_HOST
                value: postgres-svc.app.svc.cluster.local
              - name: POSTGRES_DB
                value: maindb
              - name: POSTGRES_USER
                value: mainuser
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: app-sealedsecret
                    key: POSTGRES_PASSWORD
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: home-k8s-app-job-pantry-order-reminder
  namespace: app
spec:
  schedule: "0 20 * * 1"
  timeZone: "Asia/Tokyo"
  startingDeadlineSeconds: 300
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: home-k8s-app-job-pantry-order-reminder
              image: ghcr.io/kenta-ja8/home-k8s-app-job:{{ .Values.image.jobTag }}
              args:
                - "pantry-order-reminder"
              envFrom:
              - secretRef:
                  name: app-sealedsecret
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-pvc
  namespace: app
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "maindb"
        - name: POSTGRES_USER
          value: "mainuser"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-sealedsecret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: pgdata
        persistentVolumeClaim:
          claimName: pgdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
