apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-hello-world-image-updater
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: my-image=ghcr.io/kenta-ja8/hello-world:latest
    argocd-image-updater.argoproj.io/my-image.update-strategy: digest
    argocd-image-updater.argoproj.io/my-image.platform: "linux/arm64"
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kenta-ja8/home-k8s.git
    targetRevision: main
    path: app-helm/
  project: default
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: ghcr
      api_url: https://ghcr.io
      prefix: ghcr.io
      insecure: yes
  config.yaml: |
    platforms:
      - name: linux/arm64
