apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-k8s-metrics
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kenta-ja8/home-k8s.git
    path: metrics
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
