name: Build and Push Images

on:
  push:
    paths:
      - 'src/**'
      - 'script.sh'
      - '.github/workflows/build-and-push.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64

      - uses: docker/setup-buildx-action@v3
        with:
          install: true 

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Expose ACTIONS_*
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Build and push server and job images
        run: ./script.sh buildAll
        env:
          CACHE_FROM_FLAGS: "--cache-from=type=gha"
          CACHE_TO_FLAGS: "--cache-to=type=gha,mode=max"
